# -*- coding: utf-8 -*-
"""All About List

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbPxBDisw12N-Xfvu2r-qzrWEXk2IGcB
"""

#list or array is a container to store a set of data types
#you can use a list by using square brackets [] ,seprated values
list_1=[123,987, 654, 876]
print(list_1)

#A list index is same as a string
print(list_1[1])

#slicingalist
list_1=[111,234567,123,789]
print(list_1[1:2])

#negitive indexing
print(list_1[-5:])

